version: '3'

services:
  webserver:
    extends:
      file: docker-compose-without-jupyter.yml
      service: webserver

  pelican:
    extends:
      file: docker-compose-without-jupyter.yml
      service: pelican

  jupyter:
    build:
      context: ./jupyter-container
    volumes:
      - ${BLOG_CONTENT_PATH}:/blog-content
