version: '3'

services:
  webserver:
    build:
      context: ./webserver-container
    volumes:
      - ~/peter_repos/some-folder/output:/output
    ports:
      - "8000:8000"
      - "35729:35729"

  pelican:
    build:
      context: ./pelican-container
    volumes:
      - ~/peter_repos/some-folder:/blog-content
      - ~/peter_repos/jupyter-blog:/jupyter-blog
